<<<<<<< HEAD
front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

bacula:
    resource: "@BaculaBundle/Resources/config/routing.yml"
    prefix:   /

mongo:
    resource: "@MongoBundle/Resources/config/routing.yml"
    prefix:   /
=======
mail:
    resource: "@mailBundle/Resources/config/routing.yml"
    prefix:   /mail
>>>>>>> ba944cc72262a79192505f2cafa315513d6247d8

ftp:
    resource: "@ftpBundle/Resources/config/routing.yml"
    prefix:   /ftp

login:
    resource: "@loginBundle/Resources/config/routing.yml"
    prefix:   /

webphone:
    resource: "@webphoneBundle/Resources/config/routing.yml"
    prefix:   /webphone


