ftp:
    resource: "@ftpBundle/Resources/config/routing.yml"
    prefix:   /ftp

login:
    resource: "@loginBundle/Resources/config/routing.yml"
    prefix:   /

webphone:
    resource: "@webphoneBundle/Resources/config/routing.yml"
    prefix:   /webphone


